version: 0.2
phases:
  install:
    runtime-versions:
      terraform: 1.1.0
    commands:
      - echo "Installing Terraform"
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.1.0/terraform_1.1.0_linux_amd64.zip
      - unzip terraform.zip
      - chmod +x terraform
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 962804699607.dkr.ecr.us-west-2.amazonaws.com
  build:
    commands:
      - echo build Docker image on 'date'
      - docker build -t group4-ecr-repo .
      - docker tag group4-ecr-repo:latest 962804699607.dkr.ecr.us-west-2.amazonaws.com/group4-ecr-repo:latest
      - echo "Building infrastructure with Terraform"
      - cd terraform/
      - terraform init
      - terraform apply --auto-approve
  post_build:
    commands:
      - echo build Docker image complete 'date'
      - echo push latest Docker images to ECR...
      - docker push 962804699607.dkr.ecr.us-west-2.amazonaws.com/group4-ecr-repo:latest
      - echo Writing image definition file...
      - printf '[{"name":"group4-cap2-task","imageUri":"962804699607.dkr.ecr.us-west-2.amazonaws.com/group4-ecr-repo:latest"}]' > imagedefinitions.json
      - echo "Build complete"
artifacts:
  files: imagedefinitions.json
